vich_uploader:
    db_driver: orm

    mappings:
        alumnos_foto:
            uri_prefix: subidas/fotos/alumnos
            upload_destination: '%kernel.project_dir%/public/subidas/fotos/alumnos'

        profesores_foto:
            uri_prefix: subidas/fotos/profesores
            upload_destination: '%kernel.project_dir%/public/subidas/fotos/profesores'
